### PR TITLE
feat: environment variables resolution

### PR DESCRIPTION
**Pull request by apontini**
This commit allows resolutions of env variables
within the PKGBUILD file

### CODE REVIEW

**Review by Polpetta — APPROVED** [review]
lgtm. If you wanna hack some test regarding it I wouldn't say no, otherwise it is fine as it is :heart:

**Review by M0Rf30 — CHANGES_REQUESTED** [review]
Please elaborate about the specific case that this commit solves with an example. This will be also useful to document different usages. Thanks for your efforts @apontini

**Review by Polpetta — COMMENTED** [review]
Also @apontini I thought about it right now: why not use Go template engine instead of regex? Is simpler faster and more powerful https://pkg.go.dev/text/template

**Comment by apontini** [comment]
@M0Rf30 This will allow yap to resolve environment variables in order to allow more dynamic builds. I built this for my following use case:
I have a Java project and I want to integrate pacur to it's maven build. Problem is, I can't build packages using some build specific parameters such as the project version without manually editing or using `sed` on the PKGBUILD file.

With this PR, now I can do something like:
```
pkgver=${VERSION}
```
and supply the VERSION environment variable to yap in order to compile a package with the given version, like:

```
docker run --rm -t -v $(pwd):/yap -e VERSION=1.0.1 yap/ubuntu-bionic
```
or
```
VERSION=1.0.2 yap build ubuntu example
```

**Comment by apontini** [comment]
@Polpetta I think that integrating Go templates requires some parser refactor beforehand.

**Review by M0Rf30 — APPROVED** [review]

**Comment by Polpetta** [comment]
> @Polpetta I think that integrating Go templates requires some parser refactor beforehand.

Yeah, refatoring the parser will be a pain. I've created #9, I think I'll need some help on that. Maybe @federicorispo want to check it out that together? :smirk:

**Pull request merged**
