### PR TITLE
fix: generate artifact only on output dir (close #18)

### LINKED ISSUE #18: Artifacts are generated both in the PKGBUILD folder and in the destination folder
**Describe the bug**
Artifacts are generated both in the PKGBUILD folder and in the destination folder

**To Reproduce**
Run yap with a destination folder that's not the same as the PKGBUILD folder 

**Expected behavior**
I should only have artifacts on the destination folder as a result of the build

**Logs**
No useful logs

**Desktop:**
 - OS: Parrot linux
 - Version 5.0 LTS

**Additional context**
I found this when I generated deb and rpm artifacts: these were created in the PKGBUILD directory
and in the output directory. I expect to find a single output at the end of the process. The command I
executed to test this behaviour was `cd examples && go run ../main.go build ubuntu`. If you run this,
you'll see two artifacts being generated

### PR DESCRIPTION
**Pull request by apontini**
This solves #18.
Artifact was generated both on the PKGBUILD
dir and the output directory. Now only the
latter is generated.

### CODE REVIEW

**Comment by apontini** [comment]
Still need to:
- Test with redhat and pacur packages
- remove the older artifacts copy procedure that was used before

**Comment by Polpetta** [comment]
If you use `closes` of `fixes` instead of `solves` github should automatically close the linked issue for you once merge iirc

**Comment by apontini** [comment]
@Polpetta @M0Rf30 I'd ask you to kindly test this PR for RHEL / Arch packages because docker images won't build for me for some reason. Maybe I'll open a bug about it

**Review by M0Rf30 — APPROVED** [review]
Tested right now on rocky-8

**Pull request merged**
